import { Dimensions, StyleSheet } from "react-native";
import { radius, spacing, typography } from "./tokens";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1 },
  loginContainer: { flex: 1 },
  brandSection: { alignItems: "center", marginTop: height * 0.12 },
  logo: { width: 100, height: 100 },
  name: {
    ...typography.bodyStrong,
    fontFamily: "JetBrainsMono-Medium",
    color: "#ffffff",
    textAlign: "center",
    marginTop: 90,
    alignSelf: "center",
  },
  appName: {
    ...typography.titleSmall,
    fontFamily: "JetBrainsMono-Medium",
    color: "#ffffff",
    letterSpacing: 0.5,
    textAlign: "center",
    marginTop: 90,
    alignSelf: "center",
    lineHeight: 26,
    textShadowColor: "rgba(124,58,237,0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  tagline: {
    fontSize: typography.body.fontSize,
    color: "#a3a4a8",
    letterSpacing: 1,
    textTransform: "lowercase",
  },
  illustrationContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: spacing.xl + spacing.md,
  },
  illustration: {
    width: width,
    height: width,
    maxHeight: 280,
  },
  loginSection: {
    flex: 1,
    width: "100%",
    paddingHorizontal: spacing.xl,
    paddingBottom: 80,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  googleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    borderRadius: radius.lg - 2,
    marginBottom: spacing.lg,
    marginTop: spacing.lg + spacing.xs,
    width: "100%",
    maxWidth: 300,
    shadowColor: "#091556",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 5,
  },
  googleButtonText: {
    ...typography.titleSmall,
    color: "#091556",
    marginLeft: spacing.xs,
  },
  termsText: {
    textAlign: "center",
    ...typography.caption,
    color: "rgba(255,255,255,0.7)",
    maxWidth: 280,
  },
});
