import { Dimensions, StyleSheet } from "react-native";
import { COLORS } from "../constants/theme";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingHorizontal: 16,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 5,
    backgroundColor: "white",
    borderRadius: 30,
    alignSelf: "center",
    marginTop: 12,
    marginLeft: 15,
    marginBottom: -6,
    width: 270,
  },
  menuButton: {
    marginRight: 12,
    marginLeft: 12,
    color: COLORS.primary,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 10,
  },
  textInput: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 30,
    padding: 10,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  text: {
    color: "white",
    fontWeight: "600",
    fontSize: 15,
    marginBottom: 0,
    fontFamily: "JetBrainsMono-Medium",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    marginVertical: 5,
    padding: 15,
    shadowColor: "#091556",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  name: {
    color: COLORS.primary,
    fontWeight: "bold",
    fontSize: 20,
    marginBottom: 8,
    fontFamily: "JetBrainsMono-Medium",
    flex: 1,
  },
  appName: {
    color: COLORS.primary,
    fontWeight: "bold",
    fontSize: 20,
    fontFamily: "JetBrainsMono-Medium",
    alignContent: "center",
    flex: 1,
  },
  phone: {
    color: "#4A5568",
    fontSize: 16,
    marginBottom: 2,
    letterSpacing: 0.5,
  },
  button: {
    backgroundColor: COLORS.secondary,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 18,
    alignItems: "center",
    marginVertical: 8,
  },
  buttonText: {
    color: "#FFFFFF",
    fontWeight: "bold",
    fontSize: 16,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(9,21,86,0.07)",
  },
  modalContent: {
    backgroundColor: "#ffffff",
    padding: 24,
    borderRadius: 20,
    width: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 12,
    padding: 10,
    borderRadius: 8,
    fontSize: 16,
    backgroundColor: "#F7FAFC",
    color: "#1b3872",
  },
  prefixRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
    marginBottom: 2,
  },
  prefixText: {
    color: "#1b3872",
    fontSize: 15,
  },
  removeText: {
    color: "#FF5E7E",
    marginLeft: 12,
    fontWeight: "bold",
    fontSize: 15,
  },
});