import { StyleSheet } from "react-native";
import { patterns, radius, spacing, typography } from "./tokens";

export const createProfileStyles = () =>
  StyleSheet.create({
    screen: { flex: 1 },
    headerCard: { paddingTop: 56, paddingBottom: 28, alignItems: "center", marginBottom: spacing.md },
    avatarWrap: { position: "relative", marginBottom: spacing.sm },
    avatar: { width: 88, height: 88, borderRadius: radius.pill, borderWidth: 3 },
    avatarPlaceholder: { width: 88, height: 88, borderRadius: radius.pill, borderWidth: 3, alignItems: "center", justifyContent: "center" },
    tierBadge: {
      position: "absolute",
      bottom: spacing.xxs,
      right: spacing.xxs,
      width: spacing.xl,
      height: spacing.xl,
      borderRadius: radius.pill,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
    },
    profileName: { color: "#ffffff", ...typography.title, letterSpacing: 0.3 },
    profileEmail: { color: "rgba(255,255,255,0.80)", ...typography.body, marginTop: spacing.xxs },
    tierPill: { marginTop: spacing.xs + 2, backgroundColor: "rgba(255,255,255,0.22)", paddingHorizontal: spacing.md, paddingVertical: spacing.xxs, borderRadius: radius.pill },
    tierPillText: { color: "#ffffff", ...typography.bodyStrong },
    subCard: {
      ...patterns.card,
      marginHorizontal: spacing.md,
      marginBottom: spacing.sm,
      borderRadius: radius.lg - 2,
      padding: spacing.sm + 2,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1.5,
    },
    subCardTitle: { ...typography.bodyStrong },
    subCardSubtitle: { ...typography.bodySmall, marginTop: 2 },
    statsRow: {
      marginHorizontal: spacing.md,
      marginBottom: spacing.sm,
      borderRadius: radius.lg - 2,
      flexDirection: "row",
      borderWidth: 1,
      overflow: "hidden",
    },
    statItem: { flex: 1, paddingVertical: spacing.sm + 2, alignItems: "center" },
    statValue: { ...typography.titleSmall },
    statLabel: { ...typography.caption, marginTop: 2 },
    section: {
      ...patterns.card,
      marginHorizontal: spacing.md,
      marginBottom: spacing.sm,
      borderRadius: radius.lg - 2,
    },
    sectionTitle: { ...typography.titleSmall, marginBottom: spacing.sm },
    settingRow: { flexDirection: "row", alignItems: "center", paddingVertical: spacing.sm },
    settingIconWrap: {
      width: 36,
      height: 36,
      borderRadius: radius.md - 2,
      alignItems: "center",
      justifyContent: "center",
      marginRight: spacing.sm,
    },
    settingLabel: { flex: 1, ...typography.bodyStrong },
    signOutBtn: {
      ...patterns.card,
      marginHorizontal: spacing.md,
      marginBottom: spacing.sm,
      borderRadius: radius.lg - 2,
      flexDirection: "row",
      alignItems: "center",
    },
    signOutText: { ...typography.titleSmall, fontWeight: "600" },
    modalOverlay: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "rgba(0,0,0,0.5)" },
    modalCard: { width: "92%", borderRadius: radius.xl, padding: spacing.lg, maxHeight: "88%" },
    modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: spacing.md },
    modalTitle: { ...typography.titleSmall },
    doneBtn: { ...patterns.button, paddingVertical: spacing.sm + 2, marginTop: spacing.md },
    doneBtnText: { color: "#fff", ...typography.bodyStrong },
    planBox: { borderRadius: radius.lg - 2, padding: spacing.sm + 2, marginBottom: spacing.sm, borderWidth: 1.5 },
    planName: { ...typography.titleSmall },
    planPrice: { ...typography.bodyStrong },
    planFeatureRow: { flexDirection: "row", alignItems: "center", marginTop: spacing.xxs },
    planFeatureText: { ...typography.bodySmall, marginLeft: spacing.xs - 2 },
    planUpgradeBtn: { ...patterns.button, borderRadius: radius.sm, paddingVertical: spacing.sm - 2, marginTop: spacing.sm - 2 },
    closeSpacer: { height: 40 },
    accountBlock: { marginVertical: spacing.sm - 2 },
    accountLabel: { ...typography.bodySmall, marginBottom: spacing.xxs },
    accountValue: { ...typography.titleSmall, fontWeight: "500", marginBottom: spacing.md },
    privacyText: { marginBottom: spacing.md, lineHeight: 22, ...typography.body },
  });
